# Generated by Django 2.1.5 on 2019-01-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='n_pages',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
