# Generated by Django 2.1.5 on 2019-01-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0002_book_n_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='country',
        ),
        migrations.RemoveField(
            model_name='publishingcompany',
            name='company_country',
        ),
        migrations.AlterField(
            model_name='book',
            name='n_pages',
            field=models.IntegerField(),
        ),
    ]
