# Generated by Django 2.1.5 on 2019-01-15 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0003_auto_20190115_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='n_pages',
            new_name='pages',
        ),
    ]
