# Generated by Django 2.1.5 on 2019-01-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0004_auto_20190115_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
