# Generated by Django 2.2.1 on 2019-05-23 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('made_in', models.DateTimeField(auto_now_add=True, verbose_name='made in')),
            ],
            options={
                'verbose_name': 'name',
                'verbose_name_plural': 'names',
                'ordering': ['made_in'],
            },
        ),
    ]
